---
abstract: 'Test XML and HTML content and structure with XPath expressions'
author:
  - 'David E. Wheeler <david@kineticode.com>'
build_requires:
  Module::Build: 0.30
  Test::More: 0.70
configure_requires:
  Module::Build: 0.30
generated_by: 'Module::Build version 0.3611'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-XPath
provides:
  Test::XPath:
    file: lib/Test/XPath.pm
    version: 0.13
recommends:
  HTML::Selector::XPath: 0.03
  Test::Pod: 1.20
  Test::Pod::Coverage: 1.06
requires:
  Test::Builder: 0.70
  XML::LibXML: 1.69
  perl: 5.006002
resources:
  bugtracker: http://github.com/theory/test-xpath/issues/
  homepage: http://search.cpan.org/dist/Test-XPath/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/test-xpath/tree/
version: 0.13
